baseurl:
title: the verseworks DNA
subtitle: Operating model of very different consulting company
#author: clay harmon
simple_search: http://google.com/search
description: The operationg model of a very different consulting company
name: the verseworks DNA
markdown: Kramdown
kramdown:
  input: GFM
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: pygments
#permalink: /articles/:short_year/:title
#timezone: America/New_York
#excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
#post:
#  template: _post.txt
#  extension: md
page:
  template: _page.txt
  extension: md
#editor: gvim
#git:
#  branch: master
#transfer:
#  command: rsync
#  settings: -av
#  source: _site/
#  destination: ~/Git/clayh53.github.com/
defaults:
  -
    scope:
      path: "docs"
    values:
      layout: "article"
collections:
    docs:
        output: true
company_name: "verseworks"
